name: Create artifact

on: 
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
  
    steps:
    
    ####### 4.2 #######
    
      - name: '[4.2] Clone nopCommerce'
        uses: actions/checkout@v2
        with:
          repository: 'nopSolutions/nopCommerce'
          ref: 'release-4.20'
          path: ${{ github.workspace }}/nopCommerce
        
      - name: '[4.2] Clone Misc.SalesForecasting'
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.BUILD_READ_PAT }}'
          repository: majako/nopcommerce-sales-forecasting
          ref: '4.2'
          path: ${{ github.workspace }}/nopCommerce/src/Misc.SalesForecasting
          
      - name: '[4.2] Install dotnet'
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 2.2.x
            
      - name: '[4.2] Build plugin'
        run: dotnet build ${{ github.workspace }}/nopCommerce/src/Misc.SalesForecasting/Majako.Plugin.Misc.SalesForecasting.csproj -c Release
        
      - name: '[4.2] Copy plugin to artifact'
        run: mkdir -p ${{ github.workspace }}/artifact/Majako.SalesForecasting/v4.2 && cp -r ${{ github.workspace }}/nopCommerce/src/Presentation/Nop.Web/Plugins/Misc.SalesForecasting ${{ github.workspace }}/artifact/Majako.SalesForecasting/v4.2/Misc.SalesForecasting
        
      - name: '[4.2] Remove temp nopCommerce folder'
        run: rm -rf ${{ github.workspace }}/nopCommerce

    ####### 4.3 #######

      - name: '[4.3] Clone nopCommerce'
        uses: actions/checkout@v2
        with:
          repository: 'nopSolutions/nopCommerce'
          ref: 'release-4.30'
          path: ${{ github.workspace }}/nopCommerce
        
      - name: '[4.3] Clone Misc.SalesForecasting'
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.BUILD_READ_PAT }}'
          repository: majako/nopcommerce-sales-forecasting
          ref: '4.3'
          path: ${{ github.workspace }}/nopCommerce/src/Misc.SalesForecasting
          
      - name: '[4.3] Install dotnet'
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 3.1.x
            
      - name: '[4.3] Build plugin'
        run: dotnet build ${{ github.workspace }}/nopCommerce/src/Misc.SalesForecasting/Majako.Plugin.Misc.SalesForecasting.csproj -c Release
        
      - name: '[4.3] Copy plugin to artifact'
        run: mkdir -p ${{ github.workspace }}/artifact/Majako.SalesForecasting/v4.3 && cp -r ${{ github.workspace }}/nopCommerce/src/Presentation/Nop.Web/Plugins/Misc.SalesForecasting ${{ github.workspace }}/artifact/Majako.SalesForecasting/v4.3/Misc.SalesForecasting
        
      - name: '[4.3] Remove temp nopCommerce folder'
        run: rm -rf ${{ github.workspace }}/nopCommerce
      
    ####### 4.4 #######
      
      - name: '[4.4] Clone nopCommerce'
        uses: actions/checkout@v2
        with:
          repository: 'nopSolutions/nopCommerce'
          ref: 'release-4.40.4'
          path: ${{ github.workspace }}/nopCommerce
        
      - name: '[4.4] Clone Misc.SalesForecasting'
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.BUILD_READ_PAT }}'
          repository: majako/nopcommerce-sales-forecasting
          ref: '4.4'
          path: ${{ github.workspace }}/nopCommerce/src/Misc.SalesForecasting
          
      - name: '[4.4] Install dotnet'
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
            
      - name: '[4.4] Build plugin'
        run: dotnet build ${{ github.workspace }}/nopCommerce/src/Misc.SalesForecasting/Majako.Plugin.Misc.SalesForecasting.csproj -c Release
      
      - name: '[4.4] Remove runtimes folder'
        run: rm -rf ${{ github.workspace }}/nopCommerce/src/Presentation/Nop.Web/Plugins/Misc.SalesForecasting/runtimes
        
      - name: '[4.4] Copy plugin to artifact'
        run: mkdir -p ${{ github.workspace }}/artifact/Majako.SalesForecasting/v4.4 && cp -r ${{ github.workspace }}/nopCommerce/src/Presentation/Nop.Web/Plugins/Misc.SalesForecasting ${{ github.workspace }}/artifact/Majako.SalesForecasting/v4.4/Misc.SalesForecasting
        
      - name: '[4.4] Remove temp nopCommerce folder'
        run: rm -rf ${{ github.workspace }}/nopCommerce
      
    ####### 4.5 #######
      
      - name: '[4.5] Clone nopCommerce'
        uses: actions/checkout@v2
        with:
          repository: 'nopSolutions/nopCommerce'
          ref: 'release-4.50.0-rc'
          path: ${{ github.workspace }}/nopCommerce
        
      - name: '[4.5] Clone Misc.SalesForecasting'
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.BUILD_READ_PAT }}'
          repository: majako/nopcommerce-sales-forecasting
          ref: '4.5'
          path: ${{ github.workspace }}/nopCommerce/src/Misc.SalesForecasting
          
      - name: '[4.5] Install dotnet'
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 6.0.x
            
      - name: '[4.5] Build plugin'
        run: dotnet build ${{ github.workspace }}/nopCommerce/src/Misc.SalesForecasting/Majako.Plugin.Misc.SalesForecasting.csproj -c Release
      
      - name: '[4.5] Remove runtimes folder'
        run: rm -rf ${{ github.workspace }}/nopCommerce/src/Presentation/Nop.Web/Plugins/Misc.SalesForecasting/runtimes
        
      - name: '[4.5] Copy plugin to artifact'
        run: mkdir -p ${{ github.workspace }}/artifact/Majako.SalesForecasting/v4.5 && cp -r ${{ github.workspace }}/nopCommerce/src/Presentation/Nop.Web/Plugins/Misc.SalesForecasting ${{ github.workspace }}/artifact/Majako.SalesForecasting/v4.5/Misc.SalesForecasting
        
      - name: '[4.5] Remove temp nopCommerce folder'
        run: rm -rf ${{ github.workspace }}/nopCommerce
      
   ####### all #######
      
      - name: Write to plugins.json
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: ${{ github.workspace }}/artifact/uploadedItems.json
          FILE_DATA: |
                      [
                        {
                          "Type": "Plugin",
                          "SupportedVersion": "4.20",
                          "DirectoryPath": "Majako.SalesForecasting/v4.2/Misc.SalesForecasting/",
                          "SystemName": "Misc.SalesForecasting"
                        },
                        {
                          "Type": "Plugin",
                          "SupportedVersion": "4.30",
                          "DirectoryPath": "Majako.SalesForecasting/v4.3/Misc.SalesForecasting/",
                          "SystemName": "Misc.SalesForecasting"
                        },
                        {
                          "Type": "Plugin",
                          "SupportedVersion": "4.40",
                          "DirectoryPath": "Majako.SalesForecasting/v4.4/Misc.SalesForecasting/",
                          "SystemName": "Misc.SalesForecasting"
                        },
                        {
                          "Type": "Plugin",
                          "SupportedVersion": "4.50",
                          "DirectoryPath": "Majako.SalesForecasting/v4.5/Misc.SalesForecasting/",
                          "SystemName": "Misc.SalesForecasting"
                        }
                      ]
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Get generated UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
      
      - name: Create release name
        id: release-name
        run: echo "::set-output name=release-name::Majako.SalesForecasting-${{ steps.date.outputs.date }}-${{ steps.generate-uuid.outputs.uuid }}"
      
      - name: Zip release
        run: cd ${{ github.workspace }}/artifact && zip -r ${{ steps.release-name.outputs.release-name }}.zip uploadedItems.json Majako.SalesForecasting

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
         name: ${{ steps.release-name.outputs.release-name }}
         tag_name: ${{ steps.release-name.outputs.release-name }}
         files: ${{ github.workspace }}/artifact/${{ steps.release-name.outputs.release-name }}.zip
         fail_on_unmatched_files: true
